### ISSUE TITLE
EKS | Networking ip addressing plan review

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/le-tf-infra-aws#185]
# What?
- EKS VPC design review: https://docs.aws.amazon.com/eks/latest/userguide/eks-networking.html
- Amazon EKS networking planned for growth (avoid org overlapping)

- Now, if you have pods executing in your EKS cluster and are already running out of IP addresses on your primary VPC CIDR (e.g. 10.0.0.0/20), we have two options:
  - CNI custom networking: this option uses the custom networking plugin to maintain your workers nodes’ IP addresses on your primary VPC CIDR (in this example, 10.0.0.0/20), but move your pods’ IP addresses to a larger subnet (e.g. 100.64.0.0/8). In this scenario, you can move all your pods to the new range and still use your 10.0.0.0/20 CIDR IP addresses as the source IP. However, here are some considerations you should know while using this configuration:
This solution will result in getting lesser IP addresses for the pods.
The solution is comparatively complex as it involves manual calculation & configuration of “max pods.”
The solution is not supported by EKS managed node groups.
  - Secondary CIDR with VPC: another option is to deploy new worker nodes with both the instance and pods networking on a new larger CIDR block (e.g. 100.64.0.0/8). In this scenario, after adding the new CIDR to your VPC, you can deploy another node group using the secondary CIDR and drain the original nodes to automatically redeploy the pods onto the new worker nodes.
  
### 1st Upgrade Option
- ⚠️ Move VPC subnets **_from /23_**: 
   - **IP Calc:** http://jodies.de/ipcalc?host=172.19.6.0&mask1=23&mask2=
   - **Hosts/Net:** 510 x 3 private subnets = 1530 host ip addresses

-  ✅ **_To /22_** 
   - **IP Calc:** http://jodies.de/ipcalc?host=172.19.6.0&mask1=22&mask2=
   - **Hosts/Net:** 1022 x 3 private subnets = 📈  3066 host ip addresses

-  ✅ **_To /21_** 
   - **IP Calc:** http://jodies.de/ipcalc?host=172.19.6.0&mask1=21&mask2=
   - **Hosts/Net:** 2046  x 3 private subnets = 📈 6138 host ip addresses

### 2nd Upgrade Option
- Change VPC EKS default behavior (1 private ip per pod) by assigning additional CIDR blocks to your VPC and enabling CNI custom networking, which assigns IP addresses to pods from different subnets than the node is deployed to. To use custom networking, you must enable it when you launch your nodes. You can also associate unique security groups with some of the pods running on many Amazon EC2 instance types. For more information, see Security groups for pods.

## Why?
- Amazon EC2 instances – Each Amazon EC2 node is deployed to one subnet. Each node is assigned a private IP address from a CIDR block assigned to the subnet. If the subnets were created using one of the Amazon EKS provided AWS CloudFormation templates, then nodes deployed to public subnets are automatically assigned a public IP address by the subnet. Each node is deployed with the Pod networking (CNI) which, by default, assigns each pod a private IP address from the CIDR block assigned to the subnet that the node is in and adds the IP address as a secondary IP address to one of the network interfaces attached to the instance. This AWS resource is referred to as a network interface in the AWS Management Console and the Amazon EC2 API. Therefore, we use "network interface" in this documentation instead of "elastic network interface". The term "network interface" in this documentation always means "elastic network interface".

- By default, the source IP address of each pod that communicates with resources outside of the VPC is translated through network address translation (NAT) to the primary IP address of the primary network interface attached to the node. You can change this behavior to instead have a NAT device in a private subnet translate each pod's IP address to the NAT device's IP address. For more information, see External source network address translation (SNAT).

- **Fargate pods** – Deployed to private subnets only. Each pod is assigned a private IP address from the CIDR block assigned to the subnet. Fargate does not support all pod networking options. For more information, see AWS Fargate considerations.

## How?
- **Reference Article:** https://aws.amazon.com/blogs/containers/optimize-ip-addresses-usage-by-pods-in-your-amazon-eks-cluster/
- ✅ **Plan for growth:** Size the subnets you will use for Pod networking for growth. If you have insufficient IP addresses available in the subnet that the CNI uses, your pods will not get an IP address. And the pods will remain pending until an IP address becomes available. This may impact application autoscaling and compromise its availability.
- Optimize IP addresses usage by pods in your Amazon EKS cluster | Amazon Web Services
Many enterprise customers adopt multi-account strategy to meet their business needs and at the same time reduce the security blast radius. Customers have had problems maintaining network topology because of constant growth and increased workloads. They can quickly run out of IP space while planning out the VPC Classless Inter-Domain Routing (CIDR).
- There are customers with tens or hundreds of accounts and thousands of workloads. As customers scale the EKS clusters and deploy more workloads, the number of pods managed by a cluster can grow easily above thousands of pods. Now, each of these pods will consume an IP address. This scenario might become challenging as the availability of IP addresses on a VPC is limited and it's not always possible to recreate a larger VPC or extend the current VPC's CIDR blocks. It's worth noting that both the worker nodes and the pods themselves require IP addresses. Also, the CNI will reserve IP addresses for future use.
- The impacts of using custom networking with the AWS VPC CNI (This post was inspired by https://github.com/aws/amazon-vpc-cni-k8s/issues/331.)
- You should now be able to choose the most appropriate solution if you are running into an issue of limited IP addresses in your existing VPC CIDR range. Also, it is very important to plan out your VPC CIDR ranges across your multiple accounts to make sure you do not have overlaping IP addresses requiring complex NATing resolutions. We highly recommend reading this blog that explains various networking patterns, especially for customers having hybrid environments with connectivity to their data centers.
- The issue is that having shared services connected to all the accounts with clusters will be fundamental to avoid routing problems.

### 📚 Useful resources:
- https://aws.github.io/aws-eks-best-practices/reliability/docs/networkmanagement/
- https://aws.github.io/aws-eks-best-practices/
- https://aws.github.io/aws-eks-best-practices/reliability/docs/networkmanagement/#cni-custom-networking

**Comment by exequielrafaela** [comment]
@marianod92 so the idea is to add a new entry with the info of this issue under https://leverage.binbash.com.ar/how-it-works/features/compute/k8s-eks/network (or similar) having this entry as an example (https://leverage.binbash.com.ar/how-it-works/features/network/vpc-addressing/) + adding a reference to the new EKS Network doc page.

CC: @diego-ojeda-binbash @juanmatias @angelofenoglio

**Comment by marianod92** [comment]
**- Network: VPC Adressing**
![image](https://user-images.githubusercontent.com/35702375/214444635-bda4d3e5-64c9-4c9d-a68a-f8ed0da080fd.png)


**- K8S EKS: VPC Adressing**

![image](https://user-images.githubusercontent.com/35702375/214444372-26ccf39b-657f-4eaf-b93d-e9eb4187ef71.png)
![image](https://user-images.githubusercontent.com/35702375/214444444-40b68166-641e-4d35-b49a-bdf425e36ca1.png)

**Comment by exequielrafaela** [comment]
Closed at https://github.com/binbashar/le-ref-architecture-doc/pull/142

CC: @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev
