### ISSUE TITLE
Feature |  fix: Multiple provider_urls not working with iam-assumable-role-with-oidc

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/le-tf-infra-aws#238]
## What?
Upgrade terraform iam role module for our k8s implementation in order to allow multiple OIDCs within assumable role (https://github.com/terraform-aws-modules/terraform-aws-iam/pull/115)

![image](https://user-images.githubusercontent.com/18539704/119177207-6466d200-ba42-11eb-97e7-931ad90057d9.png)

## Why? 
- Possible use case when you have multiple clusters (could be in the same or different AWS accounts)

**Comment by diego-ojeda-binbash** [comment]
This should be fixed on the newer versions of the Terraform module.
