### ISSUE TITLE
Feature | Update mysql_db module to use terraform-aws-rds latest version (v4.2.0) 

### ISSUE THREAD

**Issue by rodriguez-matias** [binbashar/le-tf-infra-aws#358]
### What?

- Updating `Binbash MySQL_DB module `to use AWS RDS Terraform module latest version (`v4.2.0`) 
(Terraform module which creates RDS resources on AWS.)

### How?
- le-tf-infra-aws/apps-devstg/us-east-1/databases-mysql --/`db_mysql.tf`
- `source version = "github.com/binbashar/terraform-aws-rds.git?ref=v3.3.0"`
- `target version = "github.com/binbashar/terraform-aws-rds.git?ref=v4.2.0" `

### Why?
-  Keeping Leverage Reference Architecture up to date.

**Comment by exequielrafaela** [comment]
@rodriguez-matias Took care of this upgrade. It was released at https://github.com/binbashar/le-tf-infra-aws/releases/tag/v1.7.2

CC: @binbashar/leverage-ref-architecture-aws-dev @binbashar/leverage-ref-architecture-aws-admin
