### ISSUE TITLE
Enhancement | Check and Update Ref Architecture layers to use terraform, module and provider resources in latest versions

### ISSUE THREAD

**Issue by rodriguez-matias** [binbashar/le-tf-infra-aws#370]
### What?
	• Keep Updated all Terraform config on every layer.
	• Keep all versions update changes registered in one location.
	
### How?
	• Check and Update versions of Terraform Core, Providers, and Modules.
	• Get the latest release version from Terraform Registry.
	• Update version constraints.
	• Test layers with new versions and report potentials issues and parameters changes.

### Why?
	• Keeping Leverage Reference Architecture up to date.

---

### ChangeLog

- Mar 28 2022: PR #359
- May 06 2022: PR #375 
- May 20 2022: PR #376
- May 21 2022: PR #381
- Jun 06 2022: PR #390
- Jun 08 2022: PR #393
- Jun 09 2022: PR #394
- Jun 28 2022: PR #396
- Jul 15 2022: PR #408
- Jul 25 2022: PR #411 
- Ago 06 2022: PR #424 
- Ago 19 2022: PR #427 
- Sep 02 2022: PR #428 
- Sep 14 2022: PR #432 
- Sep 22 2022: PR #435
- Oct 06 2022: PR  #434
- Oct 21 2022: PR #442
- Dic 05 2022: PR #450 
- Dic 13 2022: PR #451 
- Dic 19 2022: PR #453 
- Dic 28 2022: PR #454 
- Jan 16 2023: PR #459  
- Feb 07 2023: PR #473  

---

### Current Version Upgrade Status

**├── apps-devstg**
│   ├── global
│   │   └── base-identities ✅ (tf > 1.x / tf-aws > 4.x)
│   │   └── cli-test-layer   ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── us-east-1
│   │   ├── backups\ --  ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── base-certificates ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── base-network ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── base-tf-backend  ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── cdn-s3-frontend\ --   ✅ (tf > 1.x / tf-aws = 3.x)
│   │   ├── databases-aurora      ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── databases-mysql\ -- ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── databases-pgsql\ --
│   │   ├── ec2-fleet-ansible\ -- ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── k8s-eks
│   │  │    ├── cluster  ✅ (tf > 1.x / tf-aws > 4.x / tf-k8s > 2.x)
│   │  │    ├── identities  ✅ (tf > 1.x / tf-aws > 4.x / tf-k8s > 2.x)
│   │  │    ├── k8s-resources. ✅ (tf > 1.x / tf-aws > 4.x / tf-k8s > 2.x)
│   │  │    ├── k8s-workloads. ✅ (tf > 1.x / tf-aws > 4.x / tf-k8s > 2.x)
│   │  │    └── network. ✅ (tf > 1.x / tf-aws > 4.x / tf-k8s > 2.x)
│   │   ├── k8s-eks-demoapps
│   │  │    ├── cluster  ✅ (tf > 1.x / tf-aws > 4.x / tf-k8s > 2.x)
│   │  │    ├── identities  ✅ (tf > 1.x / tf-aws > 4.x / tf-k8s > 2.x)
│   │  │    ├── k8s-resources. ✅ (tf > 1.x / tf-aws > 4.x / tf-k8s > 2.x)
│   │  │    ├── k8s-workloads. ✅ (tf > 1.x / tf-aws > 4.x / tf-k8s > 2.x)
│   │  │    └── network. ✅ (tf > 1.x / tf-aws > 4.x / tf-k8s > 2.x)
│   │  ├── k8s-eks-v1.17
│   │  │    ├── cluster  ✅ (tf > 1.x / tf-aws > 4.x / tf-k8s > 2.x)
│   │  │    ├── identities  ✅ (tf > 1.x / tf-aws > 4.x / tf-k8s > 2.x)
│   │  │    ├── k8s-resources. ✅ (tf > 1.x / tf-aws > 4.x / tf-k8s > 2.x)
│   │  │    ├── k8s-workloads. ✅ (tf > 1.x / tf-aws > 4.x / tf-k8s > 2.x)
│   │  │    └── network. ✅ (tf > 1.x / tf-aws > 4.x / tf-k8s > 2.x)
│   │   ├── k8s-kind
│   │   ├── k8s-kops\ --
│   │   ├── notifications ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── security-audit ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── security-base ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── security-certs ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── security-compliance\ --
│   │   ├── security-firewall\ --    ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── security-keys ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── storage
│   │    │        └── s3-bucket-demo-files. ✅ (tf > 1.x / tf-aws > 4.x)
│   │   └── tools-cloud-nuke
│   └── us-east-2
│   ├── k8s-eks-v.1.17
│   ├── security-compliance\ --
│   └── security-keys ✅ (tf > 1.x / tf-aws > 4.x)
|
**├── apps-prd**
│   ├── global
│   │   └── base-identities  ✅ (tf > 1.x / tf-aws > 4.x)
│   └── us-east-1
│   ├── backups\ --  ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── base-network ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── base-tf-backend   ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── cdn-s3-frontend\ --   ✅ (tf > 1.x / tf-aws = 3.x)
│   ├── ec2-fleet\ -- ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── notifications ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── security-audit ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── security-base ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── security-certs ✅ (tf > 1.x/ tf-aws > 4.x)
│   ├── security-compliance\ --
│   └── security-keys ✅ (tf > 1.x / tf-aws > 4.x)
|
**├── management**
│   ├── global
│   │   ├── base-identities  ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── cost-mgmt
│   │   ├── organizations
│   │   └── sso
│   ├── us-east-1
│   │   ├── backups
│   │   ├── base-tf-backend   ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── firewall-manager
│   │   ├── notifications ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── security-audit ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── security-base ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── security-compliance
│   │   ├── security-keys ✅ (tf > 1.x / tf-aws > 4.x)
│   │   └── security-monitoring ✅ (tf > 1.x/ tf-aws > 4.x)
│   └── us-east-2
│   └── security-monitoring\ -- ✅ (tf > 1.x/ tf-aws > 4.x)
|
**├── network**
│   ├── global
│   │   └── base-identities  ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── us-east-1
│   │   ├── base-network ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── base-tf-backend   ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── network-firewall
│   │   ├── notifications ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── security-audit ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── security-base ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── security-compliance\ --
│   │   ├── security-keys ✅ (tf > 1.x / tf-aws > 4.x)
│   │   └── transit-gateway
│   └── us-east-2
│   ├── base-network ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── network-firewall
│   ├── security-compliance\ --
│   ├── security-keys ✅ (tf > 1.x / tf-aws > 4.x)
│   └── transit-gateway
|
**├── security**
│   ├── global
│   │   └── base-identities  ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── us-east-1
│   │   ├── base-tf-backend   ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── firewall-manager
│   │   ├── notifications ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── security-audit ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── security-base ✅ (tf > 1.x / tf-aws > 4.x)
│   │   ├── security-compliance\ --
│   │   ├── security-keys ✅ (tf > 1.x / tf-aws > 4.x)
│   │   └── security-monitoring ✅ (tf > 1.x/ tf-aws > 4.x)
│   └── us-east-2
│   ├── security-audit
│   ├── security-compliance\ --
│   └── security-monitoring\ --  ✅ (tf > 1.x/ tf-aws > 4.x)
|
**└── shared**
├── global
│   ├── base-dns
│   └── base-identities  ✅ (tf > 1.x / tf-aws > 4.x)
├── us-east-1
│   ├── backups  ✅ (tf > 1.x / tf-aws > 4.x) 
│   ├── base-network ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── base-tf-backend   ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── container-registry ✅ (tf > 1.3.x / tf-aws > 4.10)
│   ├── ec2-fleet\ -- ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── ec2-fleet-bastions\ --
│   ├── k8s-eks
│   ├── k8s-eks-demoapps
│   ├── k8s-eks-prd
│   ├── notifications ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── secrets-manager\ --
│   ├── security-audit ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── security-base ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── security-compliance\ --
│   ├── security-keys ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── storage 
│    │   ├── backup-gdrive  ✅ (tf > 1.x / tf-aws > 4.x)
│    │   ├── object-file-shares-for-users-list ✅ (tf > 1.x / tf-aws > 4.x)
│    │   ├── object-file-shares-for-sftp ✅ (tf > 1.x / tf-aws > 4.x)
│   ├── tools-cloud-scheduler-stop-start
│   ├── tools-eskibana
│   ├── tools-github-selfhosted-runners
│   ├── tools-jenkins\ --
│   ├── tools-managedeskibana
│   ├── tools-prometheus
│   ├── tools-vault
│   ├── tools-vpn-server ✅ (tf > 1.x / tf-aws > 4.x)
│   └── tools-webhooks\ --
└── us-east-2
├── base-network ✅ (tf > 1.x / tf-aws > 4.x)
├── container-registry ✅ (tf > 1.3.x / tf-aws > 4.10)
├── security-compliance\ --
├── security-keys ✅ (tf > 1.x / tf-aws > 4.x)
├── tools-eskibana
└── tools-prometheus

---

### Ref Links 

 - https://github.com/binbashar/le-tf-infra-aws/issues/329 
 - https://github.com/tfverch/tfvc
 - https://github.com/minamijoyo/tfupdate

**Comment by exequielrafaela** [comment]
@rodriguez-matias Thanks for creating this issue, we look forward for your next PR based on our latest discussions 🙌🏼

**Comment by exequielrafaela** [comment]
Current Versions

---
├── apps-devstg
│   ├── global
│   │   └── base-identities
│   ├── us-east-1
│   │   ├── backups\ --
│   │   ├── base-certificates ✅ (`tf > 1.x` / `tf-aws > 4.x`)
│   │   ├── base-network
│   │   ├── base-tf-backend
│   │   ├── cdn-s3-frontend\ --
│   │   ├── databases-aurora
│   │   ├── databases-mysql\ -- ✅ (`tf > 1.x` / `tf-aws > 4.x`)
│   │   ├── databases-pgsql\ --
│   │   ├── ec2-fleet-ansible\ --
│   │   ├── k8s-eks
│   │   ├── k8s-eks-demoapps
│   │   ├── k8s-kind
│   │   ├── k8s-kops\ --
│   │   ├── notifications
│   │   ├── security-audit
│   │   ├── security-base
│   │   ├── security-certs ✅ (`tf > 1.x` / `tf-aws > 4.x`)
│   │   ├── security-compliance\ --
│   │   ├── security-firewall\ --
│   │   ├── security-keys
│   │   ├── storage
│   │   └── tools-cloud-nuke
│   └── us-east-2
│       ├── k8s-eks
│       ├── security-compliance\ --
│       └── security-keys
├── apps-prd
│   ├── global
│   │   └── base-identities
│   └── us-east-1
│       ├── backups\ --
│       ├── base-network
│       ├── base-tf-backend
│       ├── cdn-s3-frontend\ --
│       ├── ec2-fleet\ --
│       ├── notifications
│       ├── security-audit
│       ├── security-base
│       ├── security-certs ✅ (`tf > 1.x`/ `tf-aws > 4.x`)
│       ├── security-compliance\ --
│       └── security-keys
├── build.env
├── build.py
├── config
│   ├── common.tfvars
│   └── common.tfvars.example
├── management
│   ├── config
│   │   ├── account.tfvars
│   │   └── backend.tfvars
│   ├── global
│   │   ├── base-identities
│   │   ├── cost-mgmt
│   │   ├── organizations
│   │   └── sso
│   ├── us-east-1
│   │   ├── backups
│   │   ├── base-tf-backend
│   │   ├── firewall-manager
│   │   ├── notifications
│   │   ├── security-audit
│   │   ├── security-base
│   │   ├── security-compliance
│   │   ├── security-keys
│   │   └── security-monitoring
│   └── us-east-2
│       └── security-monitoring\ --
├── network
│   ├── README.md
│   ├── config
│   │   ├── account.tfvars
│   │   └── backend.tfvars
│   ├── global
│   │   └── base-identities
│   ├── us-east-1
│   │   ├── base-network
│   │   ├── base-tf-backend
│   │   ├── network-firewall
│   │   ├── notifications
│   │   ├── security-audit
│   │   ├── security-base
│   │   ├── security-compliance\ --
│   │   ├── security-keys
│   │   └── transit-gateway
│   └── us-east-2
│       ├── base-network
│       ├── network-firewall
│       ├── security-compliance\ --
│       ├── security-keys
│       └── transit-gateway
├── security
│   ├── config
│   │   ├── account.tfvars
│   │   └── backend.tfvars
│   ├── global
│   │   └── base-identities
│   ├── us-east-1
│   │   ├── base-tf-backend
│   │   ├── firewall-manager
│   │   ├── notifications
│   │   ├── security-audit
│   │   ├── security-base
│   │   ├── security-compliance\ --
│   │   ├── security-keys
│   │   └── security-monitoring
│   └── us-east-2
│       ├── security-audit
│       ├── security-compliance\ --
│       └── security-monitoring\ --
└── shared
    ├── config
    │   ├── account.tfvars
    │   └── backend.tfvars
    ├── global
    │   ├── base-dns
    │   └── base-identities
    ├── us-east-1
    │   ├── backups
    │   ├── base-network
    │   ├── base-tf-backend
    │   ├── container-registry
    │   ├── ec2-fleet\ --
    │   ├── ec2-fleet-bastions\ --
    │   ├── k8s-eks
    │   ├── k8s-eks-demoapps
    │   ├── k8s-eks-prd
    │   ├── notifications
    │   ├── secrets-manager\ --
    │   ├── security-audit
    │   ├── security-base
    │   ├── security-compliance\ --
    │   ├── security-keys
    │   ├── storage
    │   ├── tools-cloud-scheduler-stop-start
    │   ├── tools-eskibana
    │   ├── tools-github-selfhosted-runners
    │   ├── tools-jenkins\ --
    │   ├── tools-managedeskibana
    │   ├── tools-prometheus
    │   ├── tools-vault
    │   ├── tools-vpn-server
    │   └── tools-webhooks\ --
    └── us-east-2
        ├── base-network
        ├── container-registry
        ├── security-compliance\ --
        ├── security-keys
        ├── tools-eskibana
        └── tools-prometheus

**Comment by exequielrafaela** [comment]
@rodriguez-matias Matu as discussed let's review all the already upgraded layers and update them with the following versions, consider this just as reference since not all the layers will strictly need the same providers.

```
terraform {
  required_version = "~> 1.1.3"

  required_providers {
    aws        = "~> 4.10"
    kubernetes = "~> 2.10"
    helm       = "~> 2.5"
    vault = "~> 2.21.0"
  }
```

CC: @diego-ojeda-binbash @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev

**Comment by rodriguez-matias** [comment]
> ```terraform
>  required_providers {
>  vault      = "~> 2.21.0"
> ```

For `tf-vault`I'll set the last functional version  `"~> 3.6.0"`

**Comment by exequielrafaela** [comment]
> > ```terraform
> >  required_providers {
> >  vault      = "~> 2.21.0"
> > ```
> 
> For `tf-vault`I'll set the last functional version `"~> 3.6.0"`

@rodriguez-matias Matu good point, well we'll need to test each specific layer with this new tf vault provider and validate if there are no breaking changes, or apply the needed updates to be able to update it. Let's us know how it goes and if you need any help with this.

**Comment by rodriguez-matias** [comment]
> ```terraform
> terraform {
>   required_version = "~> 1.1.3"
> ```

Hey @exequielrafaela I´m thinking about this constrain and if we specify the tf version like that, we are limiting the use of terraform only for versions `1.1.X.` The latest official version is at **v1.2.2**
 
Maybe we should specify the contrains liike this:
```terraform
terraform {
 required_version = "~> 1.1"  
```
So we could get all `1.X` versions.

What do you think?

**Comment by exequielrafaela** [comment]
> > ```terraform
> > terraform {
> >   required_version = "~> 1.1.3"
> > ```
> 
> Hey @exequielrafaela I´m thinking about this constrain and if we specify the tf version like that, we are limiting the use of terraform only for versions `1.1.X.` The latest official version is at **v1.2.2**
> 
> Maybe we should specify the contrains liike this:
> 
> ```terraform
> terraform {
>  required_version = "~> 1.1"  
> ```
> 
> So we could get all `1.X` versions.
> 
> tf contrains:
> 
> ```terraform
> "~> 1.1.3" = 1.1.X
> "~> 1.1"   = 1.X
> ```
> 
> What do you think?

@rodriguez-matias Matu I actually like your comment, and this is something we must document some where to keep everyone in sync. So the constraint is limited to patch versions by design since minor versions could bring breaking changes into the table. That's why we actually define the specific terraform version supported here => https://github.com/binbashar/le-tf-infra-aws/blob/7e5f1259caeebb9cc882ae535939c3ed17aff379/build.env#L9 and the associated doc here https://binbash.atlassian.net/wiki/spaces/BDPS/pages/2220687368/Releases+Versions 

In a few words we prioritize stability and controlled upgrade rollouts in general.

CC: @binbashar/leverage-ref-architecture-aws-dev @binbashar/leverage-ref-architecture-aws-admin

**Comment by rodriguez-matias** [comment]
> In a few words we prioritize stability and controlled upgrade rollouts in general, so we should keep the current planned strategy.

Yeah sure, that sounds reasonable!

**Comment by damianleys** [comment]
Enhancement | Upgrade tfstate-backend cross-account layer version https://github.com/binbashar/le-tf-infra-aws/pull/432

**Comment by rodriguez-matias** [comment]
Layer `le-tf-infra-aws/apps-devstg/us-east-1/security-firewall`  already updated by this PR #428

**Comment by rodriguez-matias** [comment]
Layer  `le-tf-infra-aws/apps-devstg/us-east-1/k8s-eks-demoapps` updated by this PR #375

**Comment by rodriguez-matias** [comment]
### Info about tfupdate tool
 
`$ tfupdate --help`

```
Usage: tfupdate [--version] [--help] <command> [<args>]

Available commands are:
    module       Update version constraints for module
    provider     Update version constraints for provider
    release      Get release version information
    terraform    Update version constraints for terraform
```

**Usage**:
- tfupdate terraform [options] <PATH>
- tfupdate provider [options] <PROVIDER_NAME> <PATH>
- tfupdate module [options] <MODULE_NAME> <PATH>
  - For modules: 
  -v  --version      A new version constraint (required)
  Automatic latest version resolution is not currently supported for modules.

**Examples**:
- `tfupdate terraform -v "~>1.1.9" . `
- `tfupdate provider -v "~>4.10" aws .`
- `tfupdate module -v "4.2.1" github.com/binbashar/terraform-aws-rds.git .`

**Changes**:
```
terraform {
 --  required_version = ">= 0.14.11"
 ++  required_version = "~> 1.1.9"

  required_providers {
   --  aws = "~> 3.0"
   ++  aws = "~> 4.10"
  }
```
```
module "bb_mysql_db" {
  -- source = "github.com/binbashar/terraform-aws-rds.git?ref=v4.2.0"
  ++ source = "github.com/binbashar/terraform-aws-rds.git?ref=v4.2.1"
```

**Comment by rodriguez-matias** [comment]
### STEPS
Overview steps to update le-ref-arch layers using tfupdate tool

1. Test the layer as is
		a. tf init 
		b. tf plan 
		c. tf apply
		d. tf destroy
		
2. Run tfupdate: will update the specified versions in terraform code.
		a. tfupdate terraform -v "\~>1.1.9" . 
		b. tfupdate provider -v "\~>4.10" aws .
		c. tfupdate module -v "4.2.1" github.com/binbashar/terraform-aws-rds.git .
		
3. Test the layer with the new versions
		a. tf init 
		b. tf plan 
		c. tf apply
		d. tf destroy
		
4. Resolve warnings and errors if needed

**Comment by rodriguez-matias** [comment]
Layer le-tf-infra-aws/apps-devstg/us-east-1/k8s-eks updated by this PR #439

**Comment by rodriguez-matias** [comment]
Layer le-tf-infra-aws/management/us-east-1/security-monitoring updated by this PR #435

**Comment by rodriguez-matias** [comment]
Layer le-tf-infra-aws/shared/us-east-1/storage updated by this PR #381

**Comment by rodriguez-matias** [comment]
Layer le-tf-infra-aws/shared/us-east-1/tools-vpn-server updated by this PR #393

**Comment by rodriguez-matias** [comment]
I leave here the latest versions to consider for updates.


```terraform
leverage cli: v1.8.0
  
terraform {
  required_version = "~> 1.2.7"

  required_providers {
    aws        = "~> 4.10"
    kubernetes = "~> 2.10"
    helm       = "~> 2.5"
    vault      = "~> 3.6.0"  
}
```

**Comment by exequielrafaela** [comment]
@rodriguez-matias I've assigned this issue to the Sprint: Jan 24 - Feb 7, 2023 so we'll then close this issue and open a new one to cover the remaining layers thanks.

CC: @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev

**Comment by rodriguez-matias** [comment]
The latest versions to consider for updates:

```
leverage cli: "v1.9.2"
  
terraform {
  required_version = "~> 1.3.5"

  required_providers {
    aws        = "~> 4.10"
    kubernetes = "~> 2.10"
    helm       = "~> 2.5"
    vault      = "~> 3.6.0"  
}
```

**Comment by diego-ojeda-binbash** [comment]
@rodriguez-matias Please use the following constraint for the Terraform version:
```
required_version = "~> 1.3"
```
That way we accept any minor upgrade of version 1 until we explicitly decide to move on to next major version.
The same goes for the versions of the providers. 🙏 

+ @exequielrafaela @juanmatias @angelofenoglio @Franr @marianod92 @joseapeinado

**Comment by rodriguez-matias** [comment]
@diego-ojeda-binbash Hi!
Actually we already discussed it with @exequielrafaela some time ago in this comment:
https://github.com/binbashar/le-tf-infra-aws/issues/370#issuecomment-1152773432

in a few words:
> ...we prioritize stability and controlled upgrade rollouts in general, so we should keep the current planned strategy (constraints limited to patch versions )...

- 

But we can go with your recommendation, if we all think it's the best approach.

**Comment by diego-ojeda-binbash** [comment]
> @diego-ojeda-binbash Hi! Actually we already discussed it with @exequielrafaela some time ago in this comment: [#370 (comment)](https://github.com/binbashar/le-tf-infra-aws/issues/370#issuecomment-1152773432)
> 
> in a few words:
> 
> > ...we prioritize stability and controlled upgrade rollouts in general, so we should keep the current planned strategy (constraints limited to patch versions )...
> 
> But we can go with your recommendation, if we all think it's the best approach.

@rodriguez-matias Yes, please let's move forward with the approach I recommended. Sorry about the confusion.
+ @exequielrafaela

**Comment by rodriguez-matias** [comment]
Closing this issue and moving the remaining tasks into the new issue #474
