### ISSUE TITLE
Fix | `/shared/us-east-2/container-registry` layer needs Terraform S3 state backend key with the `-dr suffix

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/le-tf-infra-aws#422]
### What?

- `/shared/us-east-2/container-registry` layer needs Terraform S3 state backend key with the `-dr suffix. (https://github.com/binbashar/le-tf-infra-aws/pull/420/files#r937817816)

### Why? 
- Terraform S3 backend key of us-east-1 and us-east-2 are overlapped 
- The suffix of `-dr` is to have the state in a separate and decoupled path, since they point to the same bucket, but in different paths.
- If there were 2 state buckets then we could have the same key. However, as we don't have 1 tf state bucket per region we don't have another alternative to keep them independent from each other.

**Comment by damianleys** [comment]
[Fix merged](https://github.com/binbashar/le-tf-infra-aws/pull/423)

**Comment by exequielrafaela** [comment]
Thanks @damianleys for your collaboration. Much appreciated!
