### ISSUE TITLE
Enhancement | Enable ALB access logs for EKS clusters

### ISSUE THREAD

**Issue by angelofenoglio** [binbashar/le-tf-infra-aws#477]
## Describe the Feature

Implement the required resources to store the logs and enable ALB access logs for apps-prd EKS clusters by default and optionally apps-devstg.

## Expected Behavior

n/a

## Use Case

n/a

## Describe Ideal Solution

n/a

## Alternatives Considered

Probably a good implementation would entail using the [terraform-aws-s3-log-storage](https://github.com/binbashar/terraform-aws-s3-log-storage) module to deploy the storage resources and configure the load balancer via [this annotation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#custom-attributes) in [this ingress resource](https://github.com/binbashar/le-tf-infra-aws/blob/master/apps-devstg/us-east-1/k8s-eks/k8s-components/networking-ingress.tf#L63-L85).

## Additional Context

n/a

**Comment by exequielrafaela** [comment]
@Franr I'm leaving here the [link to the slack thread](https://binbashar.slack.com/archives/GG0PJ78J3/p1677272882415569) we're we've reviewed some specifics of this issue as reference.
