### ISSUE TITLE
Feature | Remove SecOps role

### ISSUE THREAD

**Issue by Franr** [binbashar/le-tf-infra-aws#485]
## Describe the Feature

Based on [this conversation](https://binbashar.slack.com/archives/GG0PJ78J3/p1678723700118099?thread_ts=1678641756.488629&cid=GG0PJ78J3), the `SecOps` role is not necessary.
So it should be removed.

## Expected Behavior

`SecOps` role removed.

**Comment by exequielrafaela** [comment]
https://github.com/binbashar/le-tf-infra-aws/pull/487
