### ISSUE TITLE
Enhancement | Sync organizations layer between LZ template and Ref Arch

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/le-tf-infra-aws#495]
## Describe the Feature

Sync the https://github.com/binbashar/le-tf-infra-aws-template/tree/master/template/management/global/organizations code with the corresponding Ref Arch layer https://github.com/binbashar/le-tf-infra-aws/tree/master/management/global/organizations to use iterative terraform definitions that will improve the code.

**Comment by exequielrafaela** [comment]
@rodriguez-matias Matu you can generate the code via: 
1. `leverage project init`
2. `leverage project create`

**Comment by rodriguez-matias** [comment]
Hello @exequielrafaela , so if I understand correctly: 
We need to modify the template with the code of the ref-arch. Or is it the other way around? .
I assume that the ref-arch has the latest versions, right?

**Comment by exequielrafaela** [comment]
@rodriguez-matias The other way round, the LZ template has the latest code, the Ref Arch is not updated. So you can generate this code creating a new project folder and running `leverage project init` and `leverage project create` inside it.

**Comment by rodriguez-matias** [comment]
This ISSUE is closed by the PR: #509
