### ISSUE TITLE
Feature | Monitoring Metrics | Add new helm chart observavility stack to k8s-eks-demoapps

### ISSUE THREAD

**Issue by rodriguez-matias** [binbashar/le-tf-infra-aws#499]
## What?
* Add new Kube Observavility stack, created by @angelofenoglio , to the EKS DemoApps

## Why?
* New helm chart that deploys the entire obsevavility stack (prometheus + grafana) with dashboards included.

## References
* related discussion => https://binbashar.slack.com/archives/C02Q8MR5ZMK/p1680534536500669?thread_ts=1680533420.078339&cid=C02Q8MR5ZMK

**Comment by exequielrafaela** [comment]
* Ref example 1: https://github.com/binbashar/le-tf-infra-aws/blob/2bc2143764271bd028b88325d5da9436dd83fb3b/apps-devstg/us-east-1/k8s-eks/k8s-components/monitoring-metrics.tf#L41
* Ref example 2: https://github.com/binbashar/le-tf-infra-aws/blob/2bc2143764271bd028b88325d5da9436dd83fb3b/apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/monitoring-metrics.tf#L41
