### ISSUE TITLE
Add README.md to SSH code eg: shared/4_security/keys, etc

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/le-tf-infra-aws#52]
### What?
1. Add `4_security/keys` missing instructions on the ssh key. It should present how/why to create the necessary new key pair for each client, even for each client account, if necessary.
     - https://github.com/binbashar/bb-devops-tf-infra-aws/blob/master/shared/4_security/keys.tf
     - https://github.com/binbashar/bb-devops-tf-infra-aws/blob/master/apps-devstg/4_security/keys.tf

### Why?
- This helper should simplify the bootstrap and "grant" Binbash Leverage Reference Architecture conventions.
- To speed up the bootstrapping of the ref architecture implementation.
- Facilitate Binbash Customer Engineers implementation.
Reduce KT times.

**Comment by exequielrafaela** [comment]
@diego-ojeda-binbash @erpertile I think it's a good time to add this README.md considering our current EFK imple.

**Comment by diego-ojeda-binbash** [comment]
https://github.com/binbashar/le-tf-infra-aws/pull/443
