### ISSUE TITLE
Fix | Update Githubs OIDC thumbprints

### ISSUE THREAD

**Issue by angelofenoglio** [binbashar/le-tf-infra-aws#521]
## Describe the Bug
Currently we only have one thumbprint configured, but it seems that recently Github has updated their SSL certificates and so there are new thumbprints to take into consideration.

## Additional Context
https://github.com/aws-actions/configure-aws-credentials/issues/357#issuecomment-1608522964
https://github.com/orgs/community/discussions/59455
https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/

**Comment by exequielrafaela** [comment]
Internal thread as reference: https://binbashar.slack.com/archives/GG0PJ78J3/p1688583715691609
