### ISSUE TITLE
Feature | Use managed node groups per AZ

### ISSUE THREAD

**Issue by diego-ojeda-binbash** [binbashar/le-tf-infra-aws#524]
## Describe the Feature
Use managed node groups per AZ so that the Cluster Autoscaler can tell which MNG to scale and be smarter that way.
Refer to the the solution we implemented for VP.

**Comment by exequielrafaela** [comment]
https://github.com/binbashar/le-tf-infra-aws/blob/master/apps-devstg/us-east-1/k8s-eks-demoapps/cluster/eks-workers-managed.tf#L99-L117
