### ISSUE TITLE
Enhacement | Cluster addons pre requirements

### ISSUE THREAD

**Issue by eze-godoy** [binbashar/le-tf-infra-aws#530]
## What to improve?
In the [addons section](https://github.com/binbashar/le-tf-infra-aws/blob/master/apps-devstg/us-east-1/k8s-eks-demoapps/cluster/locals.tf#L40-L60) we have a problem in the execution order.

There are dependencies between addons that require IRSA roles and the security layer

## Expected Behavior
Deploy the cluster in two steps, or with a better approach in one step.

**Comment by exequielrafaela** [comment]
https://github.com/binbashar/le-tf-infra-aws/pull/549
